// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CategoryController from "./category_controller"
application.register("category", CategoryController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ShoppingListsController from "./shopping_lists_controller"
application.register("shopping-lists", ShoppingListsController)

import TasksController from "./tasks_controller"
application.register("tasks", TasksController)
